# Generated by Django 3.2.4 on 2021-06-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stamina', models.CharField(max_length=200)),
                ('perception', models.CharField(max_length=200)),
                ('endurance', models.CharField(max_length=200)),
                ('charisma', models.CharField(max_length=200)),
                ('intelligence', models.CharField(max_length=200)),
                ('agility', models.CharField(max_length=200)),
                ('luck', models.CharField(max_length=200)),
            ],
        ),
    ]
