# Generated by Django 3.2.4 on 2021-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgapp', '0002_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='endurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='luck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='perception',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='stamina',
            field=models.IntegerField(default=0),
        ),
    ]
